version: "3"

services:
  database:
    container_name: database
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data-volumes/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    networks:
      - db_network

  database_admin:
    container_name: database_admin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - db_network
    depends_on:
      - database

networks:
  db_network:
    driver: bridge
