version: '3'

services:
  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./config/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9000:9090"